name : fluxiai
services:
  db:
    image: postgres:latest
    container_name: fluxiai_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fluxiai
    ports:
      - "5432:5432"
      